# -*- coding: utf-8 -*-
"""ViaCEP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EZIayrAMXCK3AH3ZvsoH3SBGEAAW3I3d

# Realizando consumo de dados do site via cep utilizando o Python.
"""

#Importando as biliotecas necessárias
import requests
import json
import pandas as pd
import time

#Definindo a URL que será utilizada para o consumo
url = "https://viacep.com.br/ws/3711000/json/"

#Realizando chamada na API
response = None

try:
  response = requests.get(url)
except Exception as e:
  print(e)

#Exibindo o conteúdo da response

if response != None and response.status_code == 200:
  print(json.loads(response.text))

"""Agora que foi possível confirmar o funcionamento da API, será criada uma função capaz de realizar o consumo através de uma lista de CEPs."""

#Definindo lista de CEPs
lista_ceps = ['37110000', '06385125', '12903834', '17057690']

#Criando função para realizar a consulta
def consulta_ceps(lista_ceps):

  lista = []
  ceps = lista_ceps
  for i in ceps:
    url = "https://viacep.com.br/ws/" + i + "/json/"

    try:
      response = requests.get(url)
      time.sleep(0.25)
    except Exception as e:
      print(e)

    if response != None and response.status_code == 200:
      lista.append(json.loads(response.text))
    
  return lista

#Realizando consumo e atribuindo em uma lista
lista = consulta_ceps(lista_ceps)

#Criando dataframe para leitura da lista
df = pd.DataFrame(lista)
df

